import { randomUUID } from "node:crypto";
import type { DashboardLeaseInput, DashboardLeaseRow, Store } from "../store/store.ts";
import {
  type DashboardControlResponse,
  type DashboardControlServer,
  type DashboardOwnerState,
  DEFAULT_CONTROL_FOCUS_TIMEOUT_MS,
  DEFAULT_CONTROL_TIMEOUT_MS,
  requestDashboardControl,
  startDashboardControlServer,
  validateReadyDashboardControlResponse,
} from "./control.ts";
import { dashboardOwnerSocketPath } from "./runtime.ts";

export const DASHBOARD_LEASE_TTL_MS = 15_000;
export const DASHBOARD_LEASE_RENEW_INTERVAL_MS = 5_000;
export const DASHBOARD_FOLLOWER_POLL_MS = 50;

export type DashboardLeaseStore = Pick<
  Store,
  "getDashboardLease" | "tryAcquireDashboardLease" | "renewDashboardLease" | "releaseDashboardLease"
>;

export type DashboardStop =
  | { reason: "shutdown-requested" }
  | { reason: "ownership-lost"; error: Error }
  | { reason: "closed" };

export interface DashboardOwnershipOptions {
  store: DashboardLeaseStore;
  repoId: string;
  scopeId: string;
  runtimeDirectory: string;
  /** @deprecated Capabilities are generated by the owner and validated semantically by followers. */
  capability?: string;
  ownerId?: string;
  ownerPid?: number;
  now?: () => number;
  leaseTtlMs?: number;
  renewIntervalMs?: number;
  startupWaitMs?: number;
  followerPollMs?: number;
  controlTimeoutMs?: number;
  focusControlTimeoutMs?: number;
  sleep?: (ms: number) => Promise<void>;
  setInterval?: (callback: () => void, ms: number) => unknown;
  clearInterval?: (handle: unknown) => void;
  /** @deprecated PID liveness no longer gates dashboard lease takeover. */
  isProcessAlive?: (pid: number) => boolean | undefined | Promise<boolean | undefined>;
  focus?: () => boolean | Promise<boolean>;
  requestStop?: () => void | Promise<void>;
  onOwnershipLost?: (error: Error) => void | Promise<void>;
  startControlServer?: typeof startDashboardControlServer;
  requestControl?: typeof requestDashboardControl;
}

export interface DashboardFollower {
  kind: "follower";
  lease: DashboardLeaseRow;
  control: DashboardControlResponse & { state: "ready"; ok: true; launchUrl: string };
  focus(): Promise<boolean>;
}

export interface DashboardOwner {
  kind: "owner";
  ownerId: string;
  socketPath: string;
  stopped: Promise<DashboardStop>;
  getState(): DashboardOwnerState;
  isCurrent(): boolean;
  ready(launchUrl: string): Promise<void>;
  close(): Promise<void>;
}

export type DashboardOwnership = DashboardFollower | DashboardOwner;

function defaultSleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function asError(error: unknown, message: string): Error {
  return error instanceof Error ? error : new Error(message, { cause: error });
}

/** Coordinates one dashboard owner with lease and owner-specific control fencing. */
export class DashboardOwnershipCoordinator {
  private readonly options: DashboardOwnershipOptions;
  private readonly ownerId: string;
  private readonly ownerPid: number;
  private readonly socketPath: string;
  private readonly now: () => number;
  private readonly leaseTtlMs: number;
  private readonly renewIntervalMs: number;
  private readonly startupWaitMs: number;
  private readonly followerPollMs: number;
  private readonly controlTimeoutMs: number;
  private readonly focusControlTimeoutMs: number;
  private readonly sleep: (ms: number) => Promise<void>;
  private readonly setIntervalFn: (callback: () => void, ms: number) => unknown;
  private readonly clearIntervalFn: (handle: unknown) => void;
  private readonly stoppedPromise: Promise<DashboardStop>;
  private resolveStopped!: (stop: DashboardStop) => void;
  private state: DashboardOwnerState = "starting";
  private launchUrl: string | undefined;
  private server: DashboardControlServer | undefined;
  private heartbeat: unknown;
  private closePromise: Promise<void> | undefined;
  private lossPromise: Promise<void> | undefined;
  private stopSignaled = false;
  private started = false;
  private renewing = false;

  constructor(options: DashboardOwnershipOptions) {
    this.options = options;
    this.ownerId = options.ownerId ?? randomUUID();
    this.ownerPid = options.ownerPid ?? process.pid;
    this.socketPath = dashboardOwnerSocketPath(options.runtimeDirectory, options.scopeId, this.ownerId);
    this.now = options.now ?? Date.now;
    this.leaseTtlMs = options.leaseTtlMs ?? DASHBOARD_LEASE_TTL_MS;
    this.renewIntervalMs = options.renewIntervalMs ?? DASHBOARD_LEASE_RENEW_INTERVAL_MS;
    this.controlTimeoutMs = options.controlTimeoutMs ?? DEFAULT_CONTROL_TIMEOUT_MS;
    this.focusControlTimeoutMs = options.focusControlTimeoutMs ?? DEFAULT_CONTROL_FOCUS_TIMEOUT_MS;
    this.startupWaitMs = options.startupWaitMs ?? this.leaseTtlMs + this.controlTimeoutMs;
    this.followerPollMs = options.followerPollMs ?? DASHBOARD_FOLLOWER_POLL_MS;
    this.sleep = options.sleep ?? defaultSleep;
    this.setIntervalFn = options.setInterval ?? ((callback, ms) => setInterval(callback, ms));
    this.clearIntervalFn =
      options.clearInterval ?? ((handle) => clearInterval(handle as ReturnType<typeof setInterval>));
    this.stoppedPromise = new Promise((resolve) => {
      this.resolveStopped = resolve;
    });
  }

  async start(): Promise<DashboardOwnership> {
    if (this.started) throw new Error("dashboard ownership coordinator was already started");
    this.started = true;
    const deadline = this.now() + this.startupWaitMs;
    let lastFailure: Error | undefined;

    while (true) {
      const observed = this.options.store.getDashboardLease(this.options.scopeId);
      const now = this.now();
      if (!observed) {
        if (this.tryAcquire(now)) return this.becomeOwner();
      } else {
        let controlFailed = false;
        try {
          const control = await this.control(observed, "ping");
          const current = this.options.store.getDashboardLease(this.options.scopeId);
          const exactCurrent =
            current?.scopeId === observed.scopeId &&
            current.ownerId === observed.ownerId &&
            current.ownerPid === observed.ownerPid &&
            current.expiresAt > this.now();
          const exactControl = control.repoId === this.options.repoId && control.ownerId === observed.ownerId;
          if (exactCurrent && exactControl && validateReadyDashboardControlResponse(control, this.options.capability)) {
            return {
              kind: "follower",
              lease: current,
              control,
              focus: () => this.focusCurrentOwner(current),
            };
          }
          lastFailure = new Error(`dashboard owner is ${control.state}`);
        } catch (error) {
          controlFailed = true;
          lastFailure = asError(error, "dashboard control failed");
        }

        if (controlFailed) {
          const current = this.options.store.getDashboardLease(this.options.scopeId);
          const takeoverNow = this.now();
          if (current && this.sameLeaseSnapshot(current, observed) && current.expiresAt <= takeoverNow) {
            if (this.tryAcquire(takeoverNow)) return this.becomeOwner();
          }
        }
      }

      if (this.now() >= deadline) {
        throw lastFailure ?? new Error("dashboard owner did not become ready before startup wait expired");
      }
      await this.sleep(Math.min(this.followerPollMs, Math.max(0, deadline - this.now())));
    }
  }

  private lease(now: number): DashboardLeaseInput {
    return {
      scopeId: this.options.scopeId,
      ownerId: this.ownerId,
      ownerPid: this.ownerPid,
      renewedAt: now,
      expiresAt: now + this.leaseTtlMs,
    };
  }

  private tryAcquire(now: number): boolean {
    return this.options.store.tryAcquireDashboardLease(this.lease(now));
  }

  private async becomeOwner(): Promise<DashboardOwner> {
    this.heartbeat = this.setIntervalFn(() => void this.renew(), this.renewIntervalMs);
    try {
      this.server = await (this.options.startControlServer ?? startDashboardControlServer)({
        socketPath: this.socketPath,
        repoId: this.options.repoId,
        ownerId: this.ownerId,
        getState: () => this.state,
        getLaunchUrl: () => this.launchUrl,
        focus: this.options.focus,
        requestStop: () => this.requestStop(),
        timeoutMs: this.controlTimeoutMs,
        focusTimeoutMs: this.focusControlTimeoutMs,
      });
      if (!this.renewLease()) throw new Error("dashboard ownership was lost during control startup");
    } catch (error) {
      const cause = asError(error, "dashboard control startup failed");
      try {
        await this.ownershipLost(cause);
      } finally {
        this.options.store.releaseDashboardLease(this.options.scopeId, this.ownerId);
      }
      throw cause;
    }
    return {
      kind: "owner",
      ownerId: this.ownerId,
      socketPath: this.socketPath,
      stopped: this.stoppedPromise,
      getState: () => this.state,
      isCurrent: () => this.isCurrent(),
      ready: (launchUrl) => this.markReady(launchUrl),
      close: () => this.close(),
    };
  }

  private control(lease: DashboardLeaseRow, op: "ping"): Promise<DashboardControlResponse> {
    const socketPath = dashboardOwnerSocketPath(this.options.runtimeDirectory, lease.scopeId, lease.ownerId);
    return (this.options.requestControl ?? requestDashboardControl)({
      socketPath,
      repoId: this.options.repoId,
      ownerId: lease.ownerId,
      op,
      timeoutMs: this.controlTimeoutMs,
    });
  }

  private async focusCurrentOwner(lease: DashboardLeaseRow): Promise<boolean> {
    const current = this.options.store.getDashboardLease(this.options.scopeId);
    if (!this.sameCurrentLease(current, lease)) return false;
    try {
      const socketPath = dashboardOwnerSocketPath(this.options.runtimeDirectory, lease.scopeId, lease.ownerId);
      const response = await (this.options.requestControl ?? requestDashboardControl)({
        socketPath,
        repoId: this.options.repoId,
        ownerId: lease.ownerId,
        op: "focus",
        timeoutMs: this.focusControlTimeoutMs,
      });
      return (
        response.ok &&
        response.repoId === this.options.repoId &&
        response.ownerId === lease.ownerId &&
        validateReadyDashboardControlResponse(response, this.options.capability) &&
        this.sameCurrentLease(this.options.store.getDashboardLease(this.options.scopeId), lease)
      );
    } catch {
      return false;
    }
  }

  private sameCurrentLease(current: DashboardLeaseRow | undefined, expected: DashboardLeaseRow): boolean {
    return (
      current?.scopeId === expected.scopeId &&
      current.ownerId === expected.ownerId &&
      current.ownerPid === expected.ownerPid &&
      current.expiresAt > this.now()
    );
  }

  private sameLeaseSnapshot(current: DashboardLeaseRow, expected: DashboardLeaseRow): boolean {
    return (
      current.scopeId === expected.scopeId &&
      current.ownerId === expected.ownerId &&
      current.ownerPid === expected.ownerPid &&
      current.renewedAt === expected.renewedAt &&
      current.expiresAt === expected.expiresAt
    );
  }

  private isCurrent(): boolean {
    try {
      const current = this.options.store.getDashboardLease(this.options.scopeId);
      return (
        current?.scopeId === this.options.scopeId &&
        current.ownerId === this.ownerId &&
        current.ownerPid === this.ownerPid &&
        current.expiresAt > this.now()
      );
    } catch {
      return false;
    }
  }

  private async markReady(launchUrl: string): Promise<void> {
    if (!this.server || this.state !== "starting") throw new Error("dashboard owner cannot become ready now");
    if (!this.renewLease()) {
      const error = new Error("dashboard ownership was lost before readiness could be published");
      await this.ownershipLost(error);
      throw error;
    }
    this.launchUrl = launchUrl;
    this.state = "ready";
  }

  private requestStop(): void {
    if (this.state === "shutting-down") return;
    this.state = "shutting-down";
    this.signalStopped({ reason: "shutdown-requested" });
    void Promise.resolve(this.options.requestStop?.()).catch((error) => {
      void this.ownershipLost(asError(error, "dashboard shutdown callback failed"));
    });
  }

  private renewLease(): boolean {
    return this.options.store.renewDashboardLease(this.lease(this.now()));
  }

  private async renew(): Promise<void> {
    if (this.renewing || this.closePromise || this.lossPromise) return;
    this.renewing = true;
    try {
      if (!this.renewLease()) await this.ownershipLost(new Error("dashboard lease renewal was rejected"));
    } catch (error) {
      await this.ownershipLost(asError(error, "dashboard lease renewal failed"));
    } finally {
      this.renewing = false;
    }
  }

  private signalStopped(stop: DashboardStop): void {
    if (this.stopSignaled) return;
    this.stopSignaled = true;
    this.resolveStopped(stop);
  }

  private ownershipLost(error: Error): Promise<void> {
    if (this.lossPromise) return this.lossPromise;
    this.lossPromise = (async () => {
      this.state = "shutting-down";
      this.stopHeartbeat();
      this.signalStopped({ reason: "ownership-lost", error });
      try {
        await this.options.onOwnershipLost?.(error);
      } finally {
        await this.server?.close();
      }
    })();
    return this.lossPromise;
  }

  private stopHeartbeat(): void {
    if (this.heartbeat === undefined) return;
    this.clearIntervalFn(this.heartbeat);
    this.heartbeat = undefined;
  }

  private close(): Promise<void> {
    if (this.closePromise) return this.closePromise;
    this.closePromise = (async () => {
      this.state = "shutting-down";
      this.stopHeartbeat();
      this.signalStopped({ reason: "closed" });
      try {
        await this.lossPromise;
        await this.server?.close();
      } finally {
        this.options.store.releaseDashboardLease(this.options.scopeId, this.ownerId);
      }
    })();
    return this.closePromise;
  }
}

export function coordinateDashboardOwnership(options: DashboardOwnershipOptions): Promise<DashboardOwnership> {
  return new DashboardOwnershipCoordinator(options).start();
}
