import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const outputPath = path.join(root, "src/dashboard/assets.generated.ts");

const result = await build({
  absWorkingDir: root,
  assetNames: "asset-[hash]",
  bundle: true,
  charset: "utf8",
  entryNames: "app",
  entryPoints: ["web/dashboard/app.ts"],
  format: "iife",
  legalComments: "none",
  loader: {
    ".gif": "dataurl",
    ".png": "dataurl",
    ".svg": "dataurl",
    ".ttf": "dataurl",
    ".woff": "dataurl",
    ".woff2": "dataurl",
  },
  minify: true,
  outdir: "dashboard-build",
  platform: "browser",
  sourcemap: false,
  target: ["es2022"],
  write: false,
});

const js = result.outputFiles.find((file) => file.path.endsWith("app.js"));
const css = result.outputFiles.find((file) => file.path.endsWith("app.css"));
if (!js || !css || result.outputFiles.length !== 2) {
  throw new Error(`dashboard build expected one JS and one CSS output, got ${result.outputFiles.length}`);
}

function encodedLines(value: string): string {
  const encoded = Buffer.from(value, "utf8").toString("base64");
  const chunks = encoded.match(/.{1,120}/g) ?? [];
  return chunks.map((chunk) => `  ${JSON.stringify(chunk)},`).join("\n");
}

const generated = `/** Generated by scripts/build-dashboard.ts. Do not edit. */
const DASHBOARD_JS_BASE64 = [
${encodedLines(js.text)}
].join("");
const DASHBOARD_CSS_BASE64 = [
${encodedLines(css.text)}
].join("");

let dashboardJs: string | undefined;
let dashboardCss: string | undefined;

export function getDashboardJs(): string {
  return (dashboardJs ??= Buffer.from(DASHBOARD_JS_BASE64, "base64").toString("utf8"));
}

export function getDashboardCss(): string {
  return (dashboardCss ??= Buffer.from(DASHBOARD_CSS_BASE64, "base64").toString("utf8"));
}
`;
const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";

if (process.argv.includes("--check")) {
  if (current !== generated) {
    process.stderr.write("dashboard assets are stale; run npm run build:dashboard\n");
    process.exitCode = 1;
  }
} else if (current !== generated) {
  fs.writeFileSync(outputPath, generated);
}
