import fs from "node:fs";

const packageJsonUrl = new URL("../package.json", import.meta.url);
const outputUrl = new URL("../src/version.generated.ts", import.meta.url);
const parsed = JSON.parse(fs.readFileSync(packageJsonUrl, "utf8")) as { version?: unknown };

if (typeof parsed.version !== "string" || !parsed.version) {
  throw new Error("package.json must contain a string version");
}

const body = `// Generated by scripts/write-version.ts. package.json is the source of truth when running from source.\nexport const STAMPED_VERSION = ${JSON.stringify(parsed.version)};\n`;
fs.writeFileSync(outputUrl, body);
