import fs from "node:fs";

const packageJsonUrl = new URL("../package.json", import.meta.url);
const outputUrl = new URL("../src/version.generated.ts", import.meta.url);

// The committed state of version.generated.ts. `--reset` restores it after a local build so a
// real version never lands in git (CI guards this); only build-time stamping writes a real one.
const SENTINEL = "0.0.0-dev";

function packageVersion(): string {
  const parsed = JSON.parse(fs.readFileSync(packageJsonUrl, "utf8")) as { version?: unknown };
  if (typeof parsed.version !== "string" || !parsed.version) {
    throw new Error("package.json must contain a string version");
  }
  return parsed.version;
}

const version = process.argv.includes("--reset") ? SENTINEL : packageVersion();

const body = `// Generated by scripts/write-version.ts. package.json is the source of truth when running from source.
// Committed as the ${SENTINEL} sentinel; real versions are stamped only at build time (CI enforces this).
export const STAMPED_VERSION = ${JSON.stringify(version)};
`;
fs.writeFileSync(outputUrl, body);
