// Generated by scripts/write-version.ts. package.json is the source of truth when running from source.
// Committed as the 0.0.0-dev sentinel; real versions are stamped only at build time (CI enforces this).
export const STAMPED_VERSION = "0.0.0-dev";
